//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Swasey")]
[assembly: AssemblyVersion("0.8.6")]
[assembly: AssemblyFileVersion("0.8.6")]
[assembly: AssemblyInformationalVersion("0.8.6-build-0")]

