//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;

namespace Swasey.Tests.Schema.Version12 {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceListingVesion12 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceListingVesion12() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swasey.Tests.Schema.Version12.Resources.ResourceListingVesion12", typeof(ResourceListingVesion12).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations about pets.
        /// </summary>
        internal static string Apis_Pet_Description {
            get {
                return ResourceManager.GetString("Apis_Pet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pet.
        /// </summary>
        internal static string Apis_Pet_Path {
            get {
                return ResourceManager.GetString("Apis_Pet_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations about store.
        /// </summary>
        internal static string Apis_Store_Description {
            get {
                return ResourceManager.GetString("Apis_Store_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /store.
        /// </summary>
        internal static string Apis_Store_Path {
            get {
                return ResourceManager.GetString("Apis_Store_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations about user.
        /// </summary>
        internal static string Apis_User_Description {
            get {
                return ResourceManager.GetString("Apis_User_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /user.
        /// </summary>
        internal static string Apis_User_Path {
            get {
                return ResourceManager.GetString("Apis_User_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.
        /// </summary>
        internal static string ApiVersion {
            get {
                return ResourceManager.GetString("ApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oauth2.
        /// </summary>
        internal static string Authorization_Type_OAuth2 {
            get {
                return ResourceManager.GetString("Authorization_Type_OAuth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apiteam@wordnik.com.
        /// </summary>
        internal static string Info_Contact {
            get {
                return ResourceManager.GetString("Info_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a sample server Petstore server.  You can find out more about Swagger \n    at &lt;a href=\&quot;http://swagger.wordnik.com\&quot;&gt;http://swagger.wordnik.com&lt;/a&gt; or on irc.freenode.net, #swagger.  For this sample,\n    you can use the api key \&quot;special-key\&quot; to test the authorization filters.
        /// </summary>
        internal static string Info_Description {
            get {
                return ResourceManager.GetString("Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apache 2.0.
        /// </summary>
        internal static string Info_License {
            get {
                return ResourceManager.GetString("Info_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger Sample App.
        /// </summary>
        internal static string Info_Title {
            get {
                return ResourceManager.GetString("Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string Scope_Email {
            get {
                return ResourceManager.GetString("Scope_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to your email address.
        /// </summary>
        internal static string Scope_Email_Description {
            get {
                return ResourceManager.GetString("Scope_Email_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pets.
        /// </summary>
        internal static string Scope_Pets {
            get {
                return ResourceManager.GetString("Scope_Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to your pets.
        /// </summary>
        internal static string Scope_Pets_Description {
            get {
                return ResourceManager.GetString("Scope_Pets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access_code.
        /// </summary>
        internal static string TokenEndpoint_TokenName {
            get {
                return ResourceManager.GetString("TokenEndpoint_TokenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_id.
        /// </summary>
        internal static string TokenRequestEndpoint_ClientIdName {
            get {
                return ResourceManager.GetString("TokenRequestEndpoint_ClientIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_secret.
        /// </summary>
        internal static string TokenRequestEndpoint_ClientSecretName {
            get {
                return ResourceManager.GetString("TokenRequestEndpoint_ClientSecretName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.apache.org/licenses/LICENSE-2.0.html.
        /// </summary>
        internal static string Url_LicenseUrl {
            get {
                return ResourceManager.GetString("Url_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://petstore.swagger.wordnik.com/oauth/dialog.
        /// </summary>
        internal static string Url_LoginEndpoint {
            get {
                return ResourceManager.GetString("Url_LoginEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://helloreverb.com/terms/.
        /// </summary>
        internal static string Url_TermsOfServiceUrl {
            get {
                return ResourceManager.GetString("Url_TermsOfServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://petstore.swagger.wordnik.com/oauth/token.
        /// </summary>
        internal static string Url_TokenEndpoint {
            get {
                return ResourceManager.GetString("Url_TokenEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://petstore.swagger.wordnik.com/oauth/requestToken.
        /// </summary>
        internal static string Url_TokenRequestEndpoint {
            get {
                return ResourceManager.GetString("Url_TokenRequestEndpoint", resourceCulture);
            }
        }
    }
}
